title: Building things i find fun
description: Project writeups.
url: ""
baseurl: ""
markdown: kramdown
permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
